version: "2"
services: 
  web:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - db-data:/var/lib/db/data
volumes:
  db-data