version: "3.2"
services: 
  web:
    build: .
    ports: 
      - "80:3000" # requests made to the host on port 3000 are mapped to container's port 3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017" # mongodb port is mapped, so express container sends to 27017 to host, which comes back to mongo container
    volumes: 
      - db-data:/var/lib/mongo
      - type: bind
        source: ./seed
        target: /seed
        read_only: true

volumes:
  db-data:
